# Generated by Django 4.2.30 on 2026-09-19 08:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True)),
                ('user_id', models.CharField(max_length=255)),
                ('model_id', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('generate', 'Generate'), ('guard', 'Guard'), ('off_topic', 'Off Topic'), ('gate', 'Gate')], max_length=20)),
                ('input_tokens', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('output_tokens', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('config_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['request_id'], name='providers_l_request_745271_idx'), models.Index(fields=['user_id', 'created_at'], name='providers_l_user_id_6c65ce_idx'), models.Index(fields=['model_id', 'created_at'], name='providers_l_model_i_b6ef1c_idx'), models.Index(fields=['operation', 'created_at'], name='providers_l_operati_8e154d_idx'), models.Index(fields=['config_version', 'created_at'], name='providers_l_config__3dc958_idx')],
            },
        ),
    ]
