# Generated by Django 4.2.30 on 2026-09-19 08:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('response_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='limits_idem_user_id_212b97_idx'), models.Index(fields=['created_at'], name='limits_idem_created_bc9d0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('date_utc', models.DateField()),
                ('accepted_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date_utc'], name='limits_dail_date_ut_5b37e7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailycounter',
            constraint=models.UniqueConstraint(fields=('user_id', 'date_utc'), name='unique_user_date'),
        ),
    ]
