# Generated by Django 4.2.30 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idempotencyrecord',
            old_name='response_hash',
            new_name='payload_hash',
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='response',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]