# Generated by Django 4.2.30 on 2026-09-20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0002_add_payload_hash_and_response_to_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRecord',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('date_utc', models.DateField()),
                ('daily_remaining', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'date_utc'], name='limits_res_user_id_0a3d4f_idx'), models.Index(fields=['date_utc'], name='limits_res_date_ut_c4e9d9_idx'), models.Index(fields=['user_id', 'created_at'], name='limits_res_user_id_7b2e1f_idx')],
            },
        ),
    ]
