# Generated by Django 4.2.30 on 2026-09-19 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('unit_usage_key', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('reason', models.TextField()),
                ('guard_model_id', models.CharField(max_length=255)),
                ('config_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.PROTECT, related_name='block_records', to='conversations.conversation')),
                ('message_id', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.PROTECT, related_name='block_records', to='conversations.message')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation_id', 'created_at'], name='guard_block_convers_bc82c9_idx'), models.Index(fields=['user_id', 'created_at'], name='guard_block_user_id_cbbf91_idx'), models.Index(fields=['course_id', 'unit_usage_key', 'created_at'], name='guard_block_course__4acad7_idx')],
            },
        ),
    ]
