# Generated by Django 4.2.30 on 2026-09-19 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('unit_usage_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('asked', 'Asked'), ('shown', 'Shown'), ('blocked', 'Blocked'), ('no_materials', 'No Materials'), ('off_topic', 'Off Topic'), ('error', 'Error')], db_index=True, default='asked', max_length=20)),
                ('topic', models.CharField(default='other', max_length=255)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('route', models.CharField(default='default', max_length=50)),
                ('config_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_id', 'course_id', 'unit_usage_key'], name='conversatio_user_id_6e83f8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['expires_at'], name='conversatio_expires_4b00be_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='conversatio_status_ab57f0_idx'),
        ),
    ]
