# Generated by Django 4.2.30 on 2026-09-21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('conversation_id', models.UUIDField()),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
    options={
        'indexes': [models.Index(fields=['conversation_id', 'created_at'], name='conv_audit_cid_created_idx')],
    },
        ),
    ]
