# Generated by Django 4.2.30 on 2026-09-19 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('transcript', 'Transcript'), ('notes', 'Notes')], max_length=20)),
                ('ordinal', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('text', models.TextField()),
                ('start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ref', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=255)),
                ('unit_usage_key', models.CharField(max_length=255)),
                ('content_version', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INDEXING', 'Indexing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], db_index=True, default='INDEXING', max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['course_id', 'unit_usage_key'], name='materials_u_course__303454_idx'), models.Index(fields=['status'], name='materials_u_status_16289d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='unitmaterial',
            constraint=models.UniqueConstraint(fields=('unit_usage_key', 'content_version'), name='unique_content_version_per_unit'),
        ),
        migrations.AddField(
            model_name='materialsegment',
            name='material_id',
            field=models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='materials.unitmaterial'),
        ),
        migrations.AddIndex(
            model_name='materialsegment',
            index=models.Index(fields=['material_id', 'ordinal'], name='materials_m_materia_ad3340_idx'),
        ),
        migrations.AddIndex(
            model_name='materialsegment',
            index=models.Index(fields=['kind'], name='materials_m_kind_854ed2_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialsegment',
            constraint=models.UniqueConstraint(fields=('material_id', 'ordinal'), name='unique_ordinal_per_material'),
        ),
    ]
