# Generated by Django 4.2.30 on 2026-09-19

from django.db import migrations


def create_fts5_table(apps, schema_editor):
    """Create FTS5 virtual table for material segment full-text search."""
    with schema_editor.connection.cursor() as cursor:
        # Create FTS5 virtual table
        cursor.execute("""
            CREATE VIRTUAL TABLE IF NOT EXISTS material_segment_fts USING fts5(
                segment_id UNINDEXED,
                text,
                section_title,
                kind UNINDEXED,
                material_id UNINDEXED,
                ordinal UNINDEXED,
                tokenize='porter unicode61'
            )
        """)
        # Create trigger to keep FTS5 in sync with MaterialSegment (optional, we manage manually)
        # But we'll manage FTS5 manually in repository for transactional control


def drop_fts5_table(apps, schema_editor):
    """Drop FTS5 virtual table."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS material_segment_fts")


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_fts5_table, drop_fts5_table),
    ]