# Generated by Django 4.2.30 on 2026-09-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_fts5'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialsegment',
            name='unique_ordinal_per_material',
        ),
        migrations.RemoveIndex(
            model_name='materialsegment',
            name='materials_m_materia_ad3340_idx',
        ),
        migrations.AddIndex(
            model_name='materialsegment',
            index=models.Index(fields=['material_id', 'kind', 'ordinal'], name='materials_m_materia_ee7093_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialsegment',
            constraint=models.UniqueConstraint(fields=('material_id', 'kind', 'ordinal'), name='unique_ordinal_per_material_kind'),
        ),
    ]
