# Generated by Django 4.2.30 on 2026-09-19

from django.db import migrations


def recreate_fts5_table(apps, schema_editor):
    """Recreate FTS5 virtual table with source_ref column."""
    with schema_editor.connection.cursor() as cursor:
        # Drop existing table
        cursor.execute("DROP TABLE IF EXISTS material_segment_fts")
        # Create FTS5 virtual table with source_ref column
        cursor.execute("""
            CREATE VIRTUAL TABLE material_segment_fts USING fts5(
                segment_id UNINDEXED,
                text,
                section_title,
                kind UNINDEXED,
                material_id UNINDEXED,
                ordinal UNINDEXED,
                source_ref UNINDEXED,
                tokenize='porter unicode61'
            )
        """)


def drop_fts5_table(apps, schema_editor):
    """Drop FTS5 virtual table."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS material_segment_fts")


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_materialsegment_unique_ordinal_per_material_and_more'),
    ]

    operations = [
        migrations.RunPython(recreate_fts5_table, drop_fts5_table),
    ]